In [1]:
import sims.michael.joplin2obsidian.TestConfig
import org.commonmark.Extension
import org.commonmark.ext.front.matter.YamlFrontMatterExtension
import org.commonmark.ext.front.matter.YamlFrontMatterVisitor
import org.commonmark.node.AbstractVisitor
import org.commonmark.node.CustomNode
import org.commonmark.parser.Parser
import org.commonmark.renderer.html.HtmlRenderer
import org.commonmark.renderer.markdown.MarkdownRenderer

In [2]:
val markdownFiles = TestConfig.workingDirOverrideFile.walk().filter { it.extension == "md" }.toList()

In [3]:
fun displayWithLabel(label: String, data: Any) {
    DISPLAY("${label.uppercase()}:\n")
    DISPLAY(data)
    DISPLAY("\n")
}

In [4]:
%use dataframe

dataFrameOf(
    listOf("name", "path"),
    markdownFiles.flatMap { listOf(it.name, it.parent) }
)

name,path
Whirlpool Refrigerator Model _GSF26C4...,/tmp/sims.michael.joplin2obsidian.Mai...
Panasonic eneloop charger manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Amazon Basics Dual Monitor Stand Manu...,/tmp/sims.michael.joplin2obsidian.Mai...
ASUS VN248 Series Monitor User Guide.md,/tmp/sims.michael.joplin2obsidian.Mai...
Pinnacle subwoofer manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Chapin 20000 1-Gallon Poly Lawn and G...,/tmp/sims.michael.joplin2obsidian.Mai...
Sonicare toothbrush manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Raspberry Pi Manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Epiphone owner_s manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Monoprice tube amp manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Craftsman tire gauge manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Kinter amp manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Samsung 55-inch LED TV - UN55EH6000 S...,/tmp/sims.michael.joplin2obsidian.Mai...
Hoover Linx Battery Charger manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Accutek Digital Scale warranty.md,/tmp/sims.michael.joplin2obsidian.Mai...
Ubisoft Rocksmith cable warranty.md,/tmp/sims.michael.joplin2obsidian.Mai...
R8Manual_operationManual_english.pdf.md,/tmp/sims.michael.joplin2obsidian.Mai...
POLA-EN_only_Snap_User_Guide_AR5_2015...,/tmp/sims.michael.joplin2obsidian.Mai...
Huanuo Keyboard and Mouse Tray manual.md,/tmp/sims.michael.joplin2obsidian.Mai...
Whirlpool electric range manual.md,/tmp/sims.michael.joplin2obsidian.Mai...

In [5]:
val parser = Parser.builder().build()
val renderer = MarkdownRenderer.builder().build()
data class Comparison(val file: String, val original: String, val rendered: String, val match: Boolean)
val comparisons = markdownFiles.map { file ->
    val original = file.readText()
    val node = parser.parse(original)
    val rendered = renderer.render(node)
    Comparison(file.name, original, rendered, original == rendered)
}

comparisons.toDataFrame()

file,original,rendered,match
Whirlpool Refrigerator Model _GSF26C4...,--- title: 'Whirlpool Refrigerator Mo...,--- title: 'Whirlpool Refrigerator M...,false
Panasonic eneloop charger manual.md,--- title: Panasonic eneloop charger ...,--- title: Panasonic eneloop charger...,false
Amazon Basics Dual Monitor Stand Manu...,--- title: Amazon Basics Dual Monitor...,--- title: Amazon Basics Dual Monito...,false
ASUS VN248 Series Monitor User Guide.md,--- title: ASUS VN248 Series Monitor ...,--- title: ASUS VN248 Series Monitor...,false
Pinnacle subwoofer manual.md,--- title: Pinnacle subwoofer manual ...,--- title: Pinnacle subwoofer manual...,false
Chapin 20000 1-Gallon Poly Lawn and G...,--- title: Chapin 20000 1-Gallon Poly...,--- title: Chapin 20000 1-Gallon Pol...,false
Sonicare toothbrush manual.md,--- title: Sonicare toothbrush manual...,--- title: Sonicare toothbrush manua...,false
Raspberry Pi Manual.md,--- title: Raspberry Pi Manual update...,--- title: Raspberry Pi Manual updat...,false
Epiphone owner_s manual.md,--- title: Epiphone owner's manual up...,--- title: Epiphone owner's manual u...,false
Monoprice tube amp manual.md,--- title: Monoprice tube amp manual ...,--- title: Monoprice tube amp manual...,false
Craftsman tire gauge manual.md,--- title: Craftsman tire gauge manua...,--- title: Craftsman tire gauge manu...,false
Kinter amp manual.md,--- title: Kinter amp manual updated:...,--- title: Kinter amp manual updated...,false
Samsung 55-inch LED TV - UN55EH6000 S...,--- title: >- Samsung 55-inch LED T...,--- title: \>- Samsung 55-inch LED T...,false
Hoover Linx Battery Charger manual.md,--- title: Hoover Linx Battery Charge...,--- title: Hoover Linx Battery Charg...,false
Accutek Digital Scale warranty.md,--- title: Accutek Digital Scale warr...,--- title: Accutek Digital Scale war...,false
Ubisoft Rocksmith cable warranty.md,--- title: Ubisoft Rocksmith cable wa...,--- title: Ubisoft Rocksmith cable w...,false
R8Manual_operationManual_english.pdf.md,--- title: R8Manual_operationManual_e...,--- title: R8Manual\_operationManual...,false
POLA-EN_only_Snap_User_Guide_AR5_2015...,--- title: POLA-EN_only_Snap_User_Gui...,--- title: POLA-EN\_only\_Snap\_User...,false
Huanuo Keyboard and Mouse Tray manual.md,--- title: Huanuo Keyboard and Mouse ...,--- title: Huanuo Keyboard and Mouse...,false
Whirlpool electric range manual.md,--- title: Whirlpool electric range m...,--- title: Whirlpool electric range ...,false

In [6]:
val whirlpoolText = markdownFiles
    .single { it.name == "Whirlpool Refrigerator Model _GSF26C4EXY03 manual.md" }
    .readText()

val node = Parser.builder().build().parse(whirlpoolText)
val rendered = MarkdownRenderer.builder().build().render(node)

displayWithLabel("original", whirlpoolText)
displayWithLabel("rendered", rendered)

ORIGINAL:

---
title: 'Whirlpool Refrigerator Model #GSF26C4EXY03 manual'
updated: 2016-02-06 20:58:06Z
created: 2016-02-06 20:57:26Z
---

[L1004475.pdf](../_resources/L1004475.pdf)

RENDERED:

---

title: 'Whirlpool Refrigerator Model \#GSF26C4EXY03 manual'
updated: 2016-02-06 20:58:06Z
created: 2016-02-06 20:57:26Z
---

[L1004475.pdf](../_resources/L1004475.pdf)

# Front matter parsing example

In [7]:
val whirlpoolText = markdownFiles.single { it.name == "Whirlpool Refrigerator Model _GSF26C4EXY03 manual.md" }.readText()

val extensions = setOf<Extension>(YamlFrontMatterExtension.create())
val node = Parser
    .builder()
    .extensions(extensions)
    .build()
    .parse(whirlpoolText)

val visitor = object : YamlFrontMatterVisitor() {
    override fun visit(customNode: CustomNode) {
        super.visit(customNode)
    }
}.also(node::accept)

val rendered = MarkdownRenderer.builder().extensions(extensions).build().render(node)

displayWithLabel("Front matter", visitor.data)
displayWithLabel("Original text", whirlpoolText)
displayWithLabel("Re-rendered text", rendered)

FRONT MATTER:

{title=[Whirlpool Refrigerator Model #GSF26C4EXY03 manual], updated=[2016-02-06 20:58:06Z], created=[2016-02-06 20:57:26Z]}

ORIGINAL TEXT:

---
title: 'Whirlpool Refrigerator Model #GSF26C4EXY03 manual'
updated: 2016-02-06 20:58:06Z
created: 2016-02-06 20:57:26Z
---

[L1004475.pdf](../_resources/L1004475.pdf)

RE-RENDERED TEXT:

[L1004475.pdf](../_resources/L1004475.pdf)